languageCode: en-au
languageName: English (Australia)
displayName: ':flag-au:'
isoCode: en-AU
weight: 1
rtl: false
title: "Modelling Complex Fluids group"
description: 'Modelling Complex Fluids group at the University of Queensland'
copyright: '&copy; 2023 MCF'
dateFormat: 2 January 2006
params:
  recentProp: "Params.mcf"
  recentValue:
    - news
#author:
#  name: Congo
#  image: img/author.jpg
#  headline: Not your ordinary theme!
#  bio: >-
#    This is an example author bio, and although there's a stock photo of a dog
#    here, this article was actually created by a human. :dog:
#  links:
#    - twitter: 'https://twitter.com/'
#    - facebook: 'https://facebook.com/'
#    - linkedin: 'https://linkedin.com/'
#    - youtube: 'https://youtube.com/'
