baseurl: 'https://tclb.io/'
canonifyURLs: false
title: TCLB Solver
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
params:
  style: default
  description: TCLB - Templated CUDA Lattice Boltzmann Method solver
  copyright: '&copy; TCLB'
  sidebarAbout:
    - TCLB is a MPI+CUDA or MPI+CPU high-performance Computational Fluid Dynamics simulation code, based on the Lattice Boltzmann Method. It provides a clear interface for calculation of complex physics, and the implementation of new models.
  email: you@yoursite.com
  navlinks:
    - name: Pulications
      url: publication/
      home: true
    - name: About
      url: about/
    - name: Download
      url: about/download/
    - name: Documentation
      url: https://docs.tclb.io/
    - name: Tutorials
      url: https://docs.tclb.io/tutorials/model-development/1.-finite-difference-wave-equation/
  social:
#    facebook: full page or profile url in facebook
#    googleplus: full profile url in googleplus
#    email: email@example.com
#    twitter: full profile url in twitter
#    linkedin: full profile url in linkedin
#    stackoverflow: full profile url in stackoverflow
#    instagram: full profile url in instagram
    github: https://github.com/CFD-GO/TCLB
#    gitlab: full profile url in gitlab
#    youtube: full profile url in youtube
#    whatsapp: wa.me service link
taxonomies:
  author: authors
