name: Update

on:
 schedule:
   - cron: '0 12 * * 1'
 workflow_dispatch:
   pr:
     description: "Make a pull request"
     required: true
     default: true
     type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install R
      uses: r-lib/actions/setup-r@v2
    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::stringi
          any::httr
          any::yaml
    - name: Get DOI
      run: Rscript auto/get.doi.R
